# OVMF pflash (loaded with qemu.ini when booting UEFI).

[drive "ovmf-code"]
file = "ovmf/OVMF_CODE_4M.fd"
format = "raw"
if = "pflash"
readonly = "on"

[drive "ovmf-vars"]
file = "ovmf/OVMF_VARS_4M.fd"
format = "raw"
if = "pflash"
